apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
          - name: regcred
      containers:
        - name: setup
          image: docker.pkg.github.com/jlebrijo/spike/spike:latest
          envFrom:
            - configMapRef:
                name: rails-env
          command: ['rails']
          args: ['db:create', 'db:migrate', 'db:seed']
