apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
          - name: regcred
      containers:
        - name: migrate
          image: docker.pkg.github.com/jlebrijo/spike/spike:latest
          command: ['rails']
          args: ['db:migrate']
          envFrom:
            - configMapRef:
                name: rails-env
