default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  username: postgres
  password: postgres
  template: template0
  host:     localhost
  database: spike

development:
  <<: *default

test:
  <<: *default
  database: spike_test

staging:
  <<: *default

production:
  <<: *default